# Generated by Django 5.2.7 on 2025-10-28 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientoinventario',
            options={'ordering': ['-fecha'], 'verbose_name': 'Movimiento de Inventario', 'verbose_name_plural': 'Movimientos de Inventario'},
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='referencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10),
        ),
    ]
