# Generated by Django 5.2.7 on 2025-10-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='comentarios',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios / Observaciones'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero_documento',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='No. Documento'),
        ),
    ]
