# Generated by Django 5.2.7 on 2025-10-24 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('producto_final', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas_como_final', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'unique_together': {('producto_final', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_a_producir', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=12)),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='produccion.receta')),
            ],
            options={
                'verbose_name': 'Orden de producción',
                'verbose_name_plural': 'Órdenes de producción',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_por_unidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insumo_en_recetas', to='productos.producto')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='produccion.receta')),
            ],
            options={
                'verbose_name': 'Detalle de receta',
                'verbose_name_plural': 'Detalles de receta',
                'unique_together': {('receta', 'insumo')},
            },
        ),
    ]
